name: Image

on:
  workflow_run:
    workflows:
      - Build & Test
    types:
      - completed
    branches:
      - main

jobs:
  publish-docker-image:
    name: Build & Publish Docker Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64/v8
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/aoc-website:latest
            ghcr.io/${{ env.OWNER_LC }}/aoc-website:${{ github.sha }}
